#ifndef ERRORS_H
#define ERRORS_H

enum error_code
{
    NO_ERROR = 0,
    SPU_READING_ERROR,
    SPU_INPUT_FILE_ERROR,
    SPU_ARGC_ERROR,
    SPU_COND_JUMP_ERROR,
    STACK_NULLPTR,
    DATA_NULLPTR,
    LEFT_CANARY_DIED,
    RIGHT_CANARY_DIED,
    STACK_OVERFLOW,
    STACK_EMPTY,
    DIVISION_BY_ZERO
};

#endif // ERRORS_H
